export const IMAGES = {
  LlamaSocksBanner: require('../images/banners/llamasocks3.jpg'),
  BotswanaButton: require('../images/continents/africa/botswana/botswana-button.jpg'),
  // Africa: require('../images/continents/africa.jpg'),
  // Asia: require('../images/continents/asia.jpg'),
  // Australia: require('../images/continents/australia.jpg'),
  // Europe: require('../images/continents/europe.jpg'),
}

export const BANNER_CAROUSEL = {
  Banner_1: require('../images/banners/llamasocks1.jpg'),
  Banner_2: require('../images/banners/llamasocks2.jpg'),
  Banner_3: require('../images/banners/llamasocks3.jpg'),
  Banner_4: require('../images/banners/llamasocks4.jpg'),
  Banner_5: require('../images/banners/llamasocks5.jpg'),
  Banner_6: require('../images/banners/llamasocks6.jpg'),
  Banner_7: require('../images/banners/llamasocks7.jpg'),
}

// export const CONTINENT_BANNERS = {
//   AfricaBanner: 'https://i.postimg.cc/pLBh24CT/africa-banner.jpg',
//   AsiaBanner: 'https://i.postimg.cc/TYg5spWn/asia-banner.jpg',
//   EuropeBanner: 'https://i.postimg.cc/PfB8KmNt/europe-banner.jpg',
//   NorthAmericaBanner: 'https://i.postimg.cc/mg41WBQJ/north-america-banner.jpg',
//   SouthAmericaBanner: 'https://i.postimg.cc/BZ8KxhSY/south-america-banner.jpg',
// }

// export const CONTINENT_BUTTONS = {
//   AfricaButton: 'https://i.postimg.cc/d08WtqXC/africa-button.jpg',
//   AsiaButton: 'https://i.postimg.cc/rspgJ5pG/asia-button.jpg',
//   EuropeButton: 'https://i.postimg.cc/5yPKdnrk/europe-button.jpg',
//   NorthAmericaButton: 'https://i.postimg.cc/HL5Nc0JV/north-america-button.jpg',
//   OceaniaButton: 'https://i.postimg.cc/nzGwTHGx/oceania-button.jpg',
//   SouthAmericaButton: 'https://i.postimg.cc/5y9KRZsC/south-america-button.jpg',
// }

// export const COUNTRY_BANNERS = {
//   BotswanaBanner: 'https://i.postimg.cc/15LBScbY/botswana-banner.jpg',
//   EgyptBanner: 'https://i.postimg.cc/Dy0Sf91x/egypt-banner.jpg',
//   KenyaBanner: 'https://i.postimg.cc/wvJBZNRJ/kenya-banner.jpg',
//   NamibiaBanner: 'https://i.postimg.cc/Vs74Gb15/namibia-banner.jpg',
//   SouthAfricaBanner: 'https://i.postimg.cc/Kv4zB4mn/south-africa-banner.jpg',
//   TanzaniaBanner: 'https://i.postimg.cc/VNT6784J/tanzania-banner.jpg',
//   CambodiaBanner: 'https://i.postimg.cc/mDYkcRrH/cambodia-banner.jpg',
//   IndonesiaBanner: 'https://i.postimg.cc/Y0Kwcmfc/indonesia-banner.jpg',
//   JapanBanner: 'https://i.postimg.cc/bJdxt3MP/japan-banner.jpg',
//   MalaysiaBanner: 'https://i.postimg.cc/0j65qJ4P/malaysia-banner.jpg',
//   NepalBanner: 'https://i.postimg.cc/6qL8PZ4q/nepal-banner.jpg',
//   PhilippinesBanner: 'https://i.postimg.cc/mDwx63yt/philippines-banner.jpg',
//   ThailandBanner: 'https://i.postimg.cc/K8WkWB8c/thailand-banner.jpg',
//   ItalyBanner: 'https://i.postimg.cc/bNZ1VDVY/italy-banner.jpg',
//   MaltaBanner: 'https://i.postimg.cc/jqQYLczm/malta-banner.jpg',
//   BoliviaBanner: 'https://i.postimg.cc/cCRj3kqC/bolivia-banner.jpg',
//   EcuadorBanner: 'https://i.postimg.cc/4NzDrdSt/ecuador-banner.jpg',
//   PeruBanner: 'https://i.postimg.cc/RVh3dWVS/peru-banner.jpg',
// }

// export const COUNTRY_BUTTONS = {
//   AustraliaButton: 'https://i.postimg.cc/pd8fYqJM/australia-button.jpg',
//   BelizeButton: 'https://i.postimg.cc/ZqKm6MSC/belize-button.jpg',
//   BoliviaButton: 'https://i.postimg.cc/MH2Nv2Fg/bolivia-button.jpg',
//   BotswanaButton: 'https://i.postimg.cc/rFdj7YZr/botswana-button.jpg',
//   CambodiaButton: 'https://i.postimg.cc/XJSX7XnW/cambodia-button.jpg',
//   EcuadorButton: 'https://i.postimg.cc/m2fxXM8B/ecuador-button.jpg',
//   EgyptButton: 'https://i.postimg.cc/xjtk2fNk/egypt-button.jpg',
//   IndonesiaButton: 'https://i.postimg.cc/G2s1SjDJ/indonesia-button.jpg',
//   ItalyButton: 'https://i.postimg.cc/QN4pqkbn/italy-button.jpg',
//   KenyaButton: 'https://i.postimg.cc/cJPHFhC0/kenya-button.jpg',
//   MaltaButton: 'https://i.postimg.cc/1XKk2Rms/malta-button.jpg',
//   NamibiaButton: 'https://i.postimg.cc/5yk36Dp8/namibia-button.jpg',
//   NewZealandButton: 'https://i.postimg.cc/0j31vkMS/new-zealand-button.jpg',
//   PeruButton: 'https://i.postimg.cc/dVThMgyg/peru-button.jpg',
//   SouthAfricaButton: 'https://i.postimg.cc/7PKh5SrH/south-africa-button.jpg',
//   TanzaniaButton: 'https://i.postimg.cc/kgJBGwBg/tanzania-button.jpg',
//   UnitedStatesButton: 'https://i.postimg.cc/ryh8gcmM/united-states-button.jpg',
//   JapanButton: 'https://i.postimg.cc/PqSbJBSK/japan-button.jpg',
//   MalaysiaButton: 'https://i.postimg.cc/hjtPpYbJ/malaysia-button.jpg',
//   NepalButton: 'https://i.postimg.cc/Rhz3GdF2/nepal-button.jpg',
//   PhilippinesButton: 'https://i.postimg.cc/V61QRZMx/philippines-button.jpg',
//   ThailandButton: 'https://i.postimg.cc/T315QCGH/thailand-button.jpg',
// }

// export const TOP5FRONT = {
//   Botswana: {
//     1: 'https://i.postimg.cc/25XFHQdw/chobe-top-front.jpg',
//     2: 'https://i.postimg.cc/cLhc3yrP/ckgr-top-front.jpg',
//     3: 'https://i.postimg.cc/J4bx1Bmr/nxai-top-front.jpg',
//     4: 'https://i.postimg.cc/rwMJzFFS/okavango-top-front.jpg',
//     5: 'https://i.postimg.cc/XvvkcH5q/tsodilo-top-front.jpg',
//   },
//   Egypt: {
//     1: 'https://i.postimg.cc/NjTf5BFk/giza-top-front.jpg',
//     2: 'https://i.postimg.cc/k5mMSzt3/egyptdeserts-top-front.jpg',
//     3: 'https://i.postimg.cc/wvW9SB4g/nile-top-front.jpg',
//     4: 'https://i.postimg.cc/LX4HCPTx/dashur-top-front.jpg',
//     5: 'https://i.postimg.cc/QMJ8JmpB/abusimbel-top-front.jpg',
//   },
//   Kenya: {
//     1: 'https://i.postimg.cc/8kmpvNR1/masaitop.jpg',
//     2: 'https://i.postimg.cc/VvmzhV8Q/dianitop.jpg',
//     3: 'https://i.postimg.cc/c41sM2hf/kilifitop.jpg',
//     4: 'https://i.postimg.cc/vThGwtY1/merutop.jpg',
//     5: 'https://i.postimg.cc/sXpVwRb4/lamutop.jpg',
//   },
//   Namibia: {
//     1: 'https://i.postimg.cc/Pq41CB5N/sossosvlei-top-front.jpg',
//     2: 'https://i.postimg.cc/76Z00m59/kolmanskop-top-front.jpg',
//     3: 'https://i.postimg.cc/VN1jLY13/desert-top-front.jpg',
//     4: 'https://i.postimg.cc/QdcQ3BLQ/etosha-top-front.jpg',
//     5: 'https://i.postimg.cc/C1rDNkDg/twyfelfontein-top-front.jpg',
//   },
//   SouthAfrica: {
//     1: 'https://i.postimg.cc/L4g48wDT/capetowntop.jpg',
//     2: 'https://i.postimg.cc/RFNSfDBv/drakensbergtop.jpg',
//     3: 'https://i.postimg.cc/4NCf7PFT/krugertop.jpg',
//     4: 'https://i.postimg.cc/wMN94RMP/johannesburgtop.jpg',
//     5: 'https://i.postimg.cc/gJQYKHz8/wildcoasttop.jpg',
//   },
//   Tanzania: {
//     1: 'https://i.postimg.cc/66zsw0J0/tazaratop.jpg',
//     2: 'https://i.postimg.cc/D0xRg2dD/zanzibartop.jpg',
//     3: 'https://i.postimg.cc/T1dZgymg/ngorogorotop.jpg',
//     4: 'https://i.postimg.cc/C1H3RCZw/tanganyikatop.jpg',
//     5: 'https://i.postimg.cc/G2C03gmM/kilimanjarotop.jpg',
//   },
//   Bolivia: {
//     1: 'https://i.postimg.cc/1tZrFmy0/lapaztop.jpg',
//     2: 'https://i.postimg.cc/T3p0MNkb/uyunitop.jpg',
//     3: 'https://i.postimg.cc/HkR2p0Kh/tiwanakutop.jpg',
//     4: 'https://i.postimg.cc/rmCCCBpB/islatop.jpg',
//     5: 'https://i.postimg.cc/ZqNL0BzK/amazontop.jpg',
//   },
//   Ecuador: {
//     1: 'https://i.postimg.cc/90BvwgTb/quitotop.jpg',
//     2: 'https://i.postimg.cc/yd0qs88w/cuencatop.jpg',
//     3: 'https://i.postimg.cc/ZnmGRz90/galapagostop.jpg',
//     4: 'https://i.postimg.cc/KY6X6MxP/coasttop.jpg',
//     5: 'https://i.postimg.cc/gkmpc8R4/guayaquiltop.jpg',
//   },
//   Peru: {
//     1: 'https://i.postimg.cc/wMy16rrt/machupicchutop.jpg',
//     2: 'https://i.postimg.cc/9Mf4k0tY/amazontop.jpg',
//     3: 'https://i.postimg.cc/HLzc3X5L/nazcatop.jpg',
//     4: 'https://i.postimg.cc/V6HSPwKQ/sacredvalleytop.jpg',
//     5: 'https://i.postimg.cc/pdR5Dqm7/huacachinatop.jpg',
//   },
//   Italy: {
//     1: 'https://i.postimg.cc/2yVLtMw9/puglia-top.jpg',
//     2: 'https://i.postimg.cc/7PW2zPHF/sicily-top.jpg',
//     3: 'https://i.postimg.cc/Kjw3hfpG/rome-top.jpg',
//     4: 'https://i.postimg.cc/9FwqY3zr/pompeii-top.jpg',
//     5: 'https://i.postimg.cc/CxynvvfJ/alpedisiusi-top.jpg',
//   },
//   Malta: {
//     1: 'https://i.postimg.cc/fyMFc4xF/mdina-top.jpg',
//     2: 'https://i.postimg.cc/Y2xTp97w/ggantija-top.jpg',
//     3: 'https://i.postimg.cc/WbWKkHtW/valletta-top.jpg',
//     4: 'https://i.postimg.cc/RhGYGPd0/elfaroud-top.jpg',
//     5: 'https://i.postimg.cc/jddmCbqn/victoria-top.jpg',
//   },
//   Cambodia: {
//     1: 'https://i.postimg.cc/L4v4Gxg2/phnompenhtop.jpg',
//     2: 'https://i.postimg.cc/QCN8HTP2/otrestop.jpg',
//     3: 'https://i.postimg.cc/C5vFDKpz/kohrongtop.jpg',
//     4: 'https://i.postimg.cc/VL6swXXM/kampottop.jpg',
//     5: 'https://i.postimg.cc/sX4fjcnP/angkortop.jpg',
//   },
//   Indonesia: {
//     1: 'https://i.postimg.cc/Hn2vSJ69/pulauwehtop.jpg',
//     2: 'https://i.postimg.cc/02VHDwM8/bukittop.jpg',
//     3: 'https://i.postimg.cc/Z50sc5p6/togeantop.jpg',
//     4: 'https://i.postimg.cc/c1Mz1jdt/komodotop.jpg',
//     5: 'https://i.postimg.cc/3J8ckBwS/borotop.jpg',
//   },
//   Japan: {
//     1: 'https://i.postimg.cc/N0CTBR0z/tokyotop.jpg',
//     2: 'https://i.postimg.cc/SsX9sj2N/naganotop.jpg',
//     3: 'https://i.postimg.cc/3wxpst3G/tsurutop.jpg',
//     4: 'https://i.postimg.cc/3xBmfsQ7/nobotop.jpg',
//     5: 'https://i.postimg.cc/jSKyXs9Z/yonagunitop.jpg',
//   },
//   Malaysia: {
//     1: 'https://i.postimg.cc/fTcyWYLR/kualatop.jpg',
//     2: 'https://i.postimg.cc/5yv0CCSp/sepiloktop.jpg',
//     3: 'https://i.postimg.cc/L6KhMxmW/penangtop.jpg',
//     4: 'https://i.postimg.cc/wxs3PCYJ/tobtop.jpg',
//     5: 'https://i.postimg.cc/hjNvvrTf/sipidantop.jpg',
//   },
//   Nepal: {
//     1: 'https://i.postimg.cc/MT6NR20L/kathmandutop.jpg',
//     2: 'https://i.postimg.cc/Kvw6WWFK/bandipurtop.jpg',
//     3: 'https://i.postimg.cc/bvH4sNnb/pokharatop.jpg',
//     4: 'https://i.postimg.cc/MG8h6jnq/bhaktapurtop.jpg',
//     5: 'https://i.postimg.cc/y8RMCTYL/annapurnatop.jpg',
//   },
//   Thailand: {
//     1: 'https://i.postimg.cc/wMWTmYtx/angthongtop.jpg',
//     2: 'https://i.postimg.cc/MTmGzQqQ/kohphayamtop.jpg',
//     3: 'https://i.postimg.cc/ZnY5n55D/ayutthayatop.jpg',
//     4: 'https://i.postimg.cc/qBQ7Yymf/paitop.jpg',
//     5: 'https://i.postimg.cc/4dgdC5kG/railehtop.jpg',
//   },
//   Philippines: {
//     1: 'https://i.postimg.cc/906BdKwT/camiguintop.jpg',
//     2: 'https://i.postimg.cc/Rh6Rn4h4/banauetop.jpg',
//     3: 'https://i.postimg.cc/FsSMMQZM/elnidotop.jpg',
//     4: 'https://i.postimg.cc/G34wjDsh/corontop.jpg',
//     5: 'https://i.postimg.cc/44jC23zv/sanvicentetop.jpg',
//   },
// }

// export const TOP5BANNER = {
//   Bolivia: {
//     1: 'https://i.postimg.cc/Nf4dxbsQ/lapaz-banner.jpg',
//     2: 'https://i.postimg.cc/brfmmBSw/uyuni-banner.jpg',
//     3: 'https://i.postimg.cc/jSSZ3N2P/tiwanaku-banner.jpg',
//     4: 'https://i.postimg.cc/wTHWJndW/isladelsol-banner.jpg',
//     5: 'https://i.postimg.cc/prQq4JKY/amazon-banner.jpg',
//   },
//   Botswana: {
//     1: 'https://i.postimg.cc/661sh9YH/chobe-banner.jpg',
//     2: 'https://i.postimg.cc/V6fyKvxh/ckgr-banner.jpg',
//     3: 'https://i.postimg.cc/WzyQpndR/nxai-banner.jpg',
//     4: 'https://i.postimg.cc/QCC2rPxk/okavango-banner.jpg',
//     5: 'https://i.postimg.cc/sXwkqyyg/tsodilo-banner.jpg',
//   },
//   Cambodia: {
//     1: 'https://i.postimg.cc/SK8QBntN/phnom-penh-banner.jpg',
//     2: 'https://i.postimg.cc/0Qs5P9LG/otres-beach-banner.jpg',
//     3: 'https://i.postimg.cc/gJHz0fWC/koh-rong-banner.jpg',
//     4: 'https://i.postimg.cc/RhCMJXCN/kampot-banner.jpg',
//     5: 'https://i.postimg.cc/7hBq30bX/angkor-wat-banner.jpg',
//   },
//   Ecuador: {
//     1: 'https://i.postimg.cc/dtK2pCHD/quito-banner.jpg',
//     2: 'https://i.postimg.cc/bwm1ZBz2/cuenca-banner.jpg',
//     3: 'https://i.postimg.cc/rwVSFkLk/galapagos-banner.jpg',
//     4: 'https://i.postimg.cc/YSjYYz9D/coast-banner.jpg',
//     5: 'https://i.postimg.cc/J4cNLhvx/guayaquil-banner.jpg',
//   },
//   Egypt: {
//     1: 'https://i.postimg.cc/bN673qgC/giza-banner.jpg',
//     2: 'https://i.postimg.cc/FzpMtv4K/egyptdeserts-banner.jpg',
//     3: 'https://i.postimg.cc/y6T43mZz/nile-banner.jpg',
//     4: 'https://i.postimg.cc/SNN06n6Y/dashur-banner.jpg',
//     5: 'https://i.postimg.cc/HndqPxFK/abusimbel-banner.jpg',
//   },
//   Indonesia: {
//     1: 'https://i.postimg.cc/P5TCzz6z/pulau-weh-banner.jpg',
//     2: 'https://i.postimg.cc/wxRR6ByJ/bukit-lawang-banner.jpg',
//     3: 'https://i.postimg.cc/c4QKn5cL/togean-islands-banner.jpg',
//     4: 'https://i.postimg.cc/vHRgDdfK/komodo-banner.jpg',
//     5: 'https://i.postimg.cc/J0XsKTVK/borobudur-banner.jpg',
//   },
//   Italy: {
//     1: 'https://i.postimg.cc/9fBzn4k5/puglia-banner.jpg',
//     2: 'https://i.postimg.cc/R0mNd1XL/sicily-banner.jpg',
//     3: 'https://i.postimg.cc/Kzqjm6F0/rome-banner.jpg',
//     4: 'https://i.postimg.cc/V6L5QfyS/pompeii-banner.jpg',
//     5: 'https://i.postimg.cc/5yX0ys2b/alpedisiusi-banner.jpg',
//   },
//   Japan: {
//     1: 'https://i.postimg.cc/7hK38sQ4/tokyo-banner.jpg',
//     2: 'https://i.postimg.cc/xTFv6Zzy/nagano-banner.jpg',
//     3: 'https://i.postimg.cc/7YL1M4fZ/tsurunoyu-banner.jpg',
//     4: 'https://i.postimg.cc/T20qD12s/noboribetsu-banner.jpg',
//     5: 'https://i.postimg.cc/fRtxpv74/yonaguni-banner.jpg',
//   },
//   Kenya: {
//     1: 'https://i.postimg.cc/fLJZfJnv/masai-banner.jpg',
//     2: 'https://i.postimg.cc/26MYcrCN/diani-banner.jpg',
//     3: 'https://i.postimg.cc/sxWrbq2Q/kilifi-banner.jpg',
//     4: 'https://i.postimg.cc/mrdB97qD/meru-banner.jpg',
//     5: 'https://i.postimg.cc/Dzf7mxxH/lamu-banner.jpg',
//   },
//   Malaysia: {
//     1: 'https://i.postimg.cc/dV8b2G7F/kuala-lumpur-banner.jpg',
//     2: 'https://i.postimg.cc/fbD6BkX9/sepilok-banner.jpg',
//     3: 'https://i.postimg.cc/XYSMBsYx/penang-banner.jpg',
//     4: 'https://i.postimg.cc/qBFH4JfP/tip-of-borneo-banner.jpg',
//     5: 'https://i.postimg.cc/15Nhzksf/sipidan-banner.jpg',
//   },
//   Malta: {
//     1: 'https://i.postimg.cc/VLTfG9Lb/mdina-banner.jpg',
//     2: 'https://i.postimg.cc/jdCq43Kb/ggantija-banner.jpg',
//     3: 'https://i.postimg.cc/g0bYdYhz/valletta-banner.jpg',
//     4: 'https://i.postimg.cc/fyRzFB9Y/elfaroud-banner.jpg',
//     5: 'https://i.postimg.cc/bYmNbc7g/victoria-banner.jpg',
//   },
//   Namibia: {
//     1: 'https://i.postimg.cc/qqzL7GTT/sossosvlei-banner.jpg',
//     2: 'https://i.postimg.cc/XNzLztf7/kolmanskop-banner.jpg',
//     3: 'https://i.postimg.cc/5yTmQF4F/desert-banner.jpg',
//     4: 'https://i.postimg.cc/3xMBKpfs/etosha-banner.jpg',
//     5: 'https://i.postimg.cc/jdnc0vc6/twyfelfontein-banner.jpg',
//   },
//   Nepal: {
//     1: 'https://i.postimg.cc/g03S8sQq/kathmandu-banner.jpg',
//     2: 'https://i.postimg.cc/NMYN4Twh/bandipur-banner.jpg',
//     3: 'https://i.postimg.cc/mDwm6DbP/pokhara-banner.jpg',
//     4: 'https://i.postimg.cc/Y0CdcH9b/bhaktapur-banner.jpg',
//     5: 'https://i.postimg.cc/SR1DkvYq/annapurnas-banner.jpg',
//   },
//   Philippines: {
//     1: 'https://i.postimg.cc/QxXvk2J4/camiguin-banner.jpg',
//     2: 'https://i.postimg.cc/sDwqnTnV/banaue-banner.jpg',
//     3: 'https://i.postimg.cc/Bb3kzk9v/el-nido-banner.jpg',
//     4: 'https://i.postimg.cc/pVQgjWz5/coron-banner.jpg',
//     5: 'https://i.postimg.cc/L5VwFD23/san-vicente-banner.jpg',
//   },
//   Peru: {
//     1: 'https://i.postimg.cc/Bv1TKv8r/machupicchu-banner.jpg',
//     2: 'https://i.postimg.cc/C1TjHVkz/amazon-banner.jpg',
//     3: 'https://i.postimg.cc/pLrYPCPX/nazca-banner.jpg',
//     4: 'https://i.postimg.cc/sgLPxW2P/sacredvalley-banner.jpg',
//     5: 'https://i.postimg.cc/kXfvrz3p/huacachina-banner.jpg',
//   },
//   SouthAfrica: {
//     1: 'https://i.postimg.cc/7L2x8Fc1/capetown-banner.jpg',
//     2: 'https://i.postimg.cc/pTMP20bw/drakensberg-banner.jpg',
//     3: 'https://i.postimg.cc/rFVF0Y0c/kruger-banner.jpg',
//     4: 'https://i.postimg.cc/P5NXKpQR/johannesburg-banner.jpg',
//     5: 'https://i.postimg.cc/vZjQKYPH/wildcoast-banner.jpg',
//   },
//   Tanzania: {
//     1: 'https://i.postimg.cc/cHGTX3w7/tazara-banner.jpg',
//     2: 'https://i.postimg.cc/fb9BcCtT/zanzibar-banner.jpg',
//     3: 'https://i.postimg.cc/LXkD7s3c/ngorogoro-banner.jpg',
//     4: 'https://i.postimg.cc/XYX2J4n5/tanganyika-banner.jpg',
//     5: 'https://i.postimg.cc/BnymPkvV/kilimanjaro-banner.jpg',
//   },
//   Thailand: {
//     1: 'https://i.postimg.cc/zvbBvy2M/ang-thong-banner.jpg',
//     2: 'https://i.postimg.cc/cH5CdRhw/koh-phayam-banner.jpg',
//     3: 'https://i.postimg.cc/PJgqwdBq/ayutthaya-banner.jpg',
//     4: 'https://i.postimg.cc/50tjc7Bf/pai-banner.jpg',
//     5: 'https://i.postimg.cc/HLzjhD7S/raileh-banner.jpg',
//   },
// }

// export const ABOUT = {
//   "timmBanaue": 'https://i.postimg.cc/1tyjDcH3/timmbanaue.jpg',
//   "timmBorobudur": 'https://i.postimg.cc/1tMYBnCc/timmborobudur.jpg',
//   "timmDiveIndo": 'https://i.postimg.cc/cJRzK5fz/timmdiveindo.jpg',
//   "timmOnsen": 'https://i.postimg.cc/kGpY3rd2/timmonsen.jpg',
//   "timmSaxayhuaman": 'https://i.postimg.cc/rsmZPV76/timmsaxayhuaman.jpg',
// }

export const ABOUT = {
  "timmBanaue": require('../images/about/timmbanaue.jpg'),
  "timmBorobudur": require('../images/about/timmborobudur.jpg'),
  "timmDiveIndo": require('../images/about/timmdiveindo.jpg'),
  "timmOnsen": require('../images/about/timmonsen.jpg'),
  "timmSaxayhuaman": require('../images/about/timmsaxayhuaman.jpg'),
}


export const TOP5BANNER = {
  Bolivia: {
    1: require('../images/continents/south-america/bolivia/top5content/lapaz-banner.jpg'),
    2: require('../images/continents/south-america/bolivia/top5content/uyuni-banner.jpg'),
    3: require('../images/continents/south-america/bolivia/top5content/tiwanaku-banner.jpg'),
    4: require('../images/continents/south-america/bolivia/top5content/isladelsol-banner.jpg'),
    5: require('../images/continents/south-america/bolivia/top5content/amazon-banner.jpg'),
  },
  Botswana: {
    1: require('../images/continents/africa/botswana/top5content/chobe-banner.jpg'),
    2: require('../images/continents/africa/botswana/top5content/ckgr-banner.jpg'),
    3: require('../images/continents/africa/botswana/top5content/nxai-banner.jpg'),
    4: require('../images/continents/africa/botswana/top5content/okavango-banner.jpg'),
    5: require('../images/continents/africa/botswana/top5content/tsodilo-banner.jpg'),
  },
  Cambodia: {
    1: require('../images/continents/asia/cambodia/top5content/phnom-penh-banner.jpg'),
    2: require('../images/continents/asia/cambodia/top5content/otres-beach-banner.jpg'),
    3: require('../images/continents/asia/cambodia/top5content/koh-rong-banner.jpg'),
    4: require('../images/continents/asia/cambodia/top5content/kampot-banner.jpg'),
    5: require('../images/continents/asia/cambodia/top5content/angkor-wat-banner.jpg'),
  },
  Ecuador: {
    1: require('../images/continents/south-america/ecuador/top5content/quito-banner.jpg'),
    2: require('../images/continents/south-america/ecuador/top5content/cuenca-banner.jpg'),
    3: require('../images/continents/south-america/ecuador/top5content/galapagos-banner.jpg'),
    4: require('../images/continents/south-america/ecuador/top5content/coast-banner.jpg'),
    5: require('../images/continents/south-america/ecuador/top5content/guayaquil-banner.jpg'),
  },
  Egypt: {
    1: require('../images/continents/africa/egypt/top5content/giza-banner.jpg'),
    2: require('../images/continents/africa/egypt/top5content/egyptdeserts-banner.jpg'),
    3: require('../images/continents/africa/egypt/top5content/nile-banner.jpg'),
    4: require('../images/continents/africa/egypt/top5content/dashur-banner.jpg'),
    5: require('../images/continents/africa/egypt/top5content/abusimbel-banner.jpg'),
  },
  Indonesia: {
    1: require('../images/continents/asia/indonesia/top5content/pulau-weh-banner.jpg'),
    2: require('../images/continents/asia/indonesia/top5content/bukit-lawang-banner.jpg'),
    3: require('../images/continents/asia/indonesia/top5content/togean-islands-banner.jpg'),
    4: require('../images/continents/asia/indonesia/top5content/komodo-banner.jpg'),
    5: require('../images/continents/asia/indonesia/top5content/borobudur-banner.jpg'),
  },
  Italy: {
    1: require('../images/continents/europe/italy/top5content/puglia-banner.jpg'),
    2: require('../images/continents/europe/italy/top5content/sicily-banner.jpg'),
    3: require('../images/continents/europe/italy/top5content/rome-banner.jpg'),
    4: require('../images/continents/europe/italy/top5content/pompeii-banner.jpg'),
    5: require('../images/continents/europe/italy/top5content/alpedisiusi-banner.jpg'),
  },
  Japan: {
    1: require('../images/continents/asia/japan/top5content/tokyo-banner.jpg'),
    2: require('../images/continents/asia/japan/top5content/nagano-banner.jpg'),
    3: require('../images/continents/asia/japan/top5content/tsurunoyu-banner.jpg'),
    4: require('../images/continents/asia/japan/top5content/noboribetsu-banner.jpg'),
    5: require('../images/continents/asia/japan/top5content/yonaguni-banner.jpg'),
  },
  Kenya: {
    1: require('../images/continents/africa/kenya/top5content/masai-banner.jpg'),
    2: require('../images/continents/africa/kenya/top5content/diani-banner.jpg'),
    3: require('../images/continents/africa/kenya/top5content/kilifi-banner.jpg'),
    4: require('../images/continents/africa/kenya/top5content/meru-banner.jpg'),
    5: require('../images/continents/africa/kenya/top5content/lamu-banner.jpg'),
  },
  Malaysia: {
    1: require('../images/continents/asia/malaysia/top5content/kuala-lumpur-banner.jpg'),
    2: require('../images/continents/asia/malaysia/top5content/sepilok-banner.jpg'),
    3: require('../images/continents/asia/malaysia/top5content/penang-banner.jpg'),
    4: require('../images/continents/asia/malaysia/top5content/tip-of-borneo-banner.jpg'),
    5: require('../images/continents/asia/malaysia/top5content/sipidan-banner.jpg'),
  },
  Malta: {
    1: require('../images/continents/europe/malta/top5content/mdina-banner.jpg'),
    2: require('../images/continents/europe/malta/top5content/ggantija-banner.jpg'),
    3: require('../images/continents/europe/malta/top5content/valletta-banner.jpg'),
    4: require('../images/continents/europe/malta/top5content/elfaroud-banner.jpg'),
    5: require('../images/continents/europe/malta/top5content/victoria-banner.jpg'),
  },
  Namibia: {
    1: require('../images/continents/africa/namibia/top5content/sossosvlei-banner.jpg'),
    2: require('../images/continents/africa/namibia/top5content/kolmanskop-banner.jpg'),
    3: require('../images/continents/africa/namibia/top5content/desert-banner.jpg'),
    4: require('../images/continents/africa/namibia/top5content/etosha-banner.jpg'),
    5: require('../images/continents/africa/namibia/top5content/twyfelfontein-banner.jpg'),
  },
  Nepal: {
    1: require('../images/continents/asia/nepal/top5content/kathmandu-banner.jpg'),
    2: require('../images/continents/asia/nepal/top5content/bandipur-banner.jpg'),
    3: require('../images/continents/asia/nepal/top5content/pokhara-banner.jpg'),
    4: require('../images/continents/asia/nepal/top5content/bhaktapur-banner.jpg'),
    5: require('../images/continents/asia/nepal/top5content/annapurnas-banner.jpg'),
  },
  Philippines: {
    1: require('../images/continents/asia/philippines/top5content/camiguin-banner.jpg'),
    2: require('../images/continents/asia/philippines/top5content/banaue-banner.jpg'),
    3: require('../images/continents/asia/philippines/top5content/el-nido-banner.jpg'),
    4: require('../images/continents/asia/philippines/top5content/coron-banner.jpg'),
    5: require('../images/continents/asia/philippines/top5content/san-vicente-banner.jpg'),
  },
  Peru: {
    1: require('../images/continents/south-america/peru/top5content/machupicchu-banner.jpg'),
    2: require('../images/continents/south-america/peru/top5content/amazon-banner.jpg'),
    3: require('../images/continents/south-america/peru/top5content/nazca-banner.jpg'),
    4: require('../images/continents/south-america/peru/top5content/sacredvalley-banner.jpg'),
    5: require('../images/continents/south-america/peru/top5content/huacachina-banner.jpg'),
  },
  SouthAfrica: {
    1: require('../images/continents/africa/south-africa/top5content/capetown-banner.jpg'),
    2: require('../images/continents/africa/south-africa/top5content/drakensberg-banner.jpg'),
    3: require('../images/continents/africa/south-africa/top5content/kruger-banner.jpg'),
    4: require('../images/continents/africa/south-africa/top5content/johannesburg-banner.jpg'),
    5: require('../images/continents/africa/south-africa/top5content/wildcoast-banner.jpg'),
  },
  Tanzania: {
    1: require('../images/continents/africa/tanzania/top5content/tazara-banner.jpg'),
    2: require('../images/continents/africa/tanzania/top5content/zanzibar-banner.jpg'),
    3: require('../images/continents/africa/tanzania/top5content/ngorogoro-banner.jpg'),
    4: require('../images/continents/africa/tanzania/top5content/tanganyika-banner.jpg'),
    5: require('../images/continents/africa/tanzania/top5content/kilimanjaro-banner.jpg'),
  },
  Thailand: {
    1: require('../images/continents/asia/thailand/top5content/ang-thong-banner.jpg'),
    2: require('../images/continents/asia/thailand/top5content/koh-phayam-banner.jpg'),
    3: require('../images/continents/asia/thailand/top5content/ayutthaya-banner.jpg'),
    4: require('../images/continents/asia/thailand/top5content/pai-banner.jpg'),
    5: require('../images/continents/asia/thailand/top5content/raileh-banner.jpg'),
  }
}

export const TOP5FRONT = {
  Botswana: {
    1: require('../images/continents/africa/botswana/top5/chobe-top-front.jpg'),
    2: require('../images/continents/africa/botswana/top5/ckgr-top-front.jpg'),
    3: require('../images/continents/africa/botswana/top5/nxai-top-front.jpg'),
    4: require('../images/continents/africa/botswana/top5/okavango-top-front.jpg'),
    5: require('../images/continents/africa/botswana/top5/tsodilo-top-front.jpg'),
  },
  Egypt: {
    1: require('../images/continents/africa/egypt/top5/giza-top-front.jpg'),
    2: require('../images/continents/africa/egypt/top5/egyptdeserts-top-front.jpg'),
    3: require('../images/continents/africa/egypt/top5/nile-top-front.jpg'),
    4: require('../images/continents/africa/egypt/top5/dashur-top-front.jpg'),
    5: require('../images/continents/africa/egypt/top5/abusimbel-top-front.jpg'),
  },
  Kenya: {
    1: require('../images/continents/africa/kenya/top5/masaitop.jpg'),
    2: require('../images/continents/africa/kenya/top5/dianitop.jpg'),
    3: require('../images/continents/africa/kenya/top5/kilifitop.jpg'),
    4: require('../images/continents/africa/kenya/top5/merutop.jpg'),
    5: require('../images/continents/africa/kenya/top5/lamutop.jpg'),
  },
  Namibia: {
    1: require('../images/continents/africa/namibia/top5/sossosvlei-top-front.jpg'),
    2: require('../images/continents/africa/namibia/top5/kolmanskop-top-front.jpg'),
    3: require('../images/continents/africa/namibia/top5/desert-top-front.jpg'),
    4: require('../images/continents/africa/namibia/top5/etosha-top-front.jpg'),
    5: require('../images/continents/africa/namibia/top5/twyfelfontein-top-front.jpg'),
  },
  SouthAfrica: {
    1: require('../images/continents/africa/south-africa/top5/capetowntop.jpg'),
    2: require('../images/continents/africa/south-africa/top5/drakensbergtop.jpg'),
    3: require('../images/continents/africa/south-africa/top5/krugertop.jpg'),
    4: require('../images/continents/africa/south-africa/top5/johannesburgtop.jpg'),
    5: require('../images/continents/africa/south-africa/top5/wildcoasttop.jpg'),
  },
  Tanzania: {
    1: require('../images/continents/africa/tanzania/top5/tazaratop.jpg'),
    2: require('../images/continents/africa/tanzania/top5/zanzibartop.jpg'),
    3: require('../images/continents/africa/tanzania/top5/ngorogorotop.jpg'),
    4: require('../images/continents/africa/tanzania/top5/tanganyikatop.jpg'),
    5: require('../images/continents/africa/tanzania/top5/kilimanjarotop.jpg'),
  },
  Bolivia: {
    1: require('../images/continents/south-america/bolivia/top5/lapaztop.jpg'),
    2: require('../images/continents/south-america/bolivia/top5/uyunitop.jpg'),
    3: require('../images/continents/south-america/bolivia/top5/tiwanakutop.jpg'),
    4: require('../images/continents/south-america/bolivia/top5/islatop.jpg'),
    5: require('../images/continents/south-america/bolivia/top5/amazontop.jpg'),
  },
  Ecuador: {
    1: require('../images/continents/south-america/ecuador/top5/quitotop.jpg'),
    2: require('../images/continents/south-america/ecuador/top5/cuencatop.jpg'),
    3: require('../images/continents/south-america/ecuador/top5/galapagostop.jpg'),
    4: require('../images/continents/south-america/ecuador/top5/coasttop.jpg'),
    5: require('../images/continents/south-america/ecuador/top5/guayaquiltop.jpg'),
  },
  Peru: {
    1: require('../images/continents/south-america/peru/top5/machupicchutop.jpg'),
    2: require('../images/continents/south-america/peru/top5/amazontop.jpg'),
    3: require('../images/continents/south-america/peru/top5/nazcatop.jpg'),
    4: require('../images/continents/south-america/peru/top5/sacredvalleytop.jpg'),
    5: require('../images/continents/south-america/peru/top5/huacachinatop.jpg'),
  },
  Italy: {
    1: require('../images/continents/europe/italy/top5/puglia-top.jpg'),
    2: require('../images/continents/europe/italy/top5/sicily-top.jpg'),
    3: require('../images/continents/europe/italy/top5/rome-top.jpg'),
    4: require('../images/continents/europe/italy/top5/pompeii-top.jpg'),
    5: require('../images/continents/europe/italy/top5/alpedisiusi-top.jpg'),
  },
  Malta: {
    1: require('../images/continents/europe/malta/top5/mdina-top.jpg'),
    2: require('../images/continents/europe/malta/top5/ggantija-top.jpg'),
    3: require('../images/continents/europe/malta/top5/valletta-top.jpg'),
    4: require('../images/continents/europe/malta/top5/elfaroud-top.jpg'),
    5: require('../images/continents/europe/malta/top5/victoria-top.jpg'),
  },
  Cambodia: {
    1: require('../images/continents/asia/cambodia/top5/phnompenhtop.jpg'),
    2: require('../images/continents/asia/cambodia/top5/otrestop.jpg'),
    3: require('../images/continents/asia/cambodia/top5/kohrongtop.jpg'),
    4: require('../images/continents/asia/cambodia/top5/kampottop.jpg'),
    5: require('../images/continents/asia/cambodia/top5/angkortop.jpg'),
  },
  Indonesia: {
    1: require('../images/continents/asia/indonesia/top5/pulauwehtop.jpg'),
    2: require('../images/continents/asia/indonesia/top5/bukittop.jpg'),
    3: require('../images/continents/asia/indonesia/top5/togeantop.jpg'),
    4: require('../images/continents/asia/indonesia/top5/komodotop.jpg'),
    5: require('../images/continents/asia/indonesia/top5/borotop.jpg'),
  },
  Japan: {
    1: require('../images/continents/asia/japan/top5/tokyotop.jpg'),
    2: require('../images/continents/asia/japan/top5/naganotop.jpg'),
    3: require('../images/continents/asia/japan/top5/tsurutop.jpg'),
    4: require('../images/continents/asia/japan/top5/nobotop.jpg'),
    5: require('../images/continents/asia/japan/top5/yonagunitop.jpg'),
  },
  Malaysia: {
    1: require('../images/continents/asia/malaysia/top5/kualatop.jpg'),
    2: require('../images/continents/asia/malaysia/top5/sepiloktop.jpg'),
    3: require('../images/continents/asia/malaysia/top5/penangtop.jpg'),
    4: require('../images/continents/asia/malaysia/top5/tobtop.jpg'),
    5: require('../images/continents/asia/malaysia/top5/sipidantop.jpg'),
  },
  Nepal: {
    1: require('../images/continents/asia/nepal/top5/kathmandutop.jpg'),
    2: require('../images/continents/asia/nepal/top5/bandipurtop.jpg'),
    3: require('../images/continents/asia/nepal/top5/pokharatop.jpg'),
    4: require('../images/continents/asia/nepal/top5/bhaktapurtop.jpg'),
    5: require('../images/continents/asia/nepal/top5/annapurnatop.jpg'),
  },
  Thailand: {
    1: require('../images/continents/asia/thailand/top5/angthongtop.jpg'),
    2: require('../images/continents/asia/thailand/top5/kohphayamtop.jpg'),
    3: require('../images/continents/asia/thailand/top5/ayutthayatop.jpg'),
    4: require('../images/continents/asia/thailand/top5/paitop.jpg'),
    5: require('../images/continents/asia/thailand/top5/railehtop.jpg'),
  },
  Philippines: {
    1: require('../images/continents/asia/philippines/top5/camiguintop.jpg'),
    2: require('../images/continents/asia/philippines/top5/banauetop.jpg'),
    3: require('../images/continents/asia/philippines/top5/elnidotop.jpg'),
    4: require('../images/continents/asia/philippines/top5/corontop.jpg'),
    5: require('../images/continents/asia/philippines/top5/sanvicentetop.jpg'),
  },
}

export const COUNTRY_BANNERS = {
  BotswanaBanner: require('../images/continents/africa/botswana/botswana-banner.jpg'),
  EgyptBanner: require('../images/continents/africa/egypt/egypt-banner.jpg'),
  KenyaBanner: require('../images/continents/africa/kenya/kenya-banner.jpg'),
  NamibiaBanner: require('../images/continents/africa/namibia/namibia-banner.jpg'),
  SouthAfricaBanner: require('../images/continents/africa/south-africa/south-africa-banner.jpg'),
  TanzaniaBanner: require('../images/continents/africa/tanzania/tanzania-banner.jpg'),
  CambodiaBanner: require('../images/continents/asia/cambodia/cambodia-banner.jpg'),
  IndonesiaBanner: require('../images/continents/asia/indonesia/indonesia-banner.jpg'),
  JapanBanner: require('../images/continents/asia/japan/japan-banner.jpg'),
  MalaysiaBanner: require('../images/continents/asia/malaysia/malaysia-banner.jpg'),
  NepalBanner: require('../images/continents/asia/nepal/nepal-banner.jpg'),
  PhilippinesBanner: require('../images/continents/asia/philippines/philippines-banner.jpg'),
  ThailandBanner: require('../images/continents/asia/thailand/thailand-banner.jpg'),
  ItalyBanner: require('../images/continents/europe/italy/italy-banner.jpg'),
  MaltaBanner: require('../images/continents/europe/malta/malta-banner.jpg'),
  BoliviaBanner: require('../images/continents/south-america/bolivia/bolivia-banner.jpg'),
  EcuadorBanner: require('../images/continents/south-america/ecuador/ecuador-banner.jpg'),
  PeruBanner: require('../images/continents/south-america/peru/peru-banner.jpg'),
}

export const COUNTRY_BUTTONS = {
  AustraliaButton: require('../images/continents/oceania/australia/australia-button.jpg'),
  BelizeButton: require('../images/continents/north-america/belize/belize-button.jpg'),
  BoliviaButton: require('../images/continents/south-america/bolivia/bolivia-button.jpg'),
  BotswanaButton: require('../images/continents/africa/botswana/botswana-button.jpg'),
  CambodiaButton: require('../images/continents/asia/cambodia/cambodia-button.jpg'),
  EcuadorButton: require('../images/continents/south-america/ecuador/ecuador-button.jpg'),
  EgyptButton: require('../images/continents/africa/egypt/egypt-button.jpg'),
  IndonesiaButton: require('../images/continents/asia/indonesia/indonesia-button.jpg'),
  ItalyButton: require('../images/continents/europe/italy/italy-button.jpg'),
  KenyaButton: require('../images/continents/africa/kenya/kenya-button.jpg'),
  MaltaButton: require('../images/continents/europe/malta/malta-button.jpg'),
  NamibiaButton: require('../images/continents/africa/namibia/namibia-button.jpg'),
  NewZealandButton: require('../images/continents/oceania/new-zealand/new-zealand-button.jpg'),
  PeruButton: require('../images/continents/south-america/peru/peru-button.jpg'),
  SouthAfricaButton: require('../images/continents/africa/south-africa/south-africa-button.jpg'),
  TanzaniaButton: require('../images/continents/africa/tanzania/tanzania-button.jpg'),
  UnitedStatesButton: require('../images/continents/north-america/united-states/united-states-button.jpg'),
  JapanButton: require('../images/continents/asia/japan/japan-button.jpg'),
  MalaysiaButton: require('../images/continents/asia/malaysia/malaysia-button.jpg'),
  NepalButton: require('../images/continents/asia/nepal/nepal-button.jpg'),
  PhilippinesButton: require('../images/continents/asia/philippines/philippines-button.jpg'),
  ThailandButton: require('../images/continents/asia/thailand/thailand-button.jpg'),
}

export const CONTINENT_BANNERS = {
  AfricaBanner: require('../images/continents/continentBanners/africa-banner.jpg'),
  AsiaBanner: require('../images/continents/continentBanners/asia-banner.jpg'),
  EuropeBanner: require('../images/continents/continentBanners/europe-banner.jpg'),
  NorthAmericaBanner: require('../images/continents/continentBanners/north-america-banner.jpg'),
  SouthAmericaBanner: require('../images/continents/continentBanners/south-america-banner.jpg'),
}

export const CONTINENT_BUTTONS = {
  AfricaButton: require('../images/continents/continentButtons/africa-button.jpg'),
  AsiaButton: require('../images/continents/continentButtons/asia-button.jpg'),
  EuropeButton: require('../images/continents/continentButtons/europe-button.jpg'),
  NorthAmericaButton: require('../images/continents/continentButtons/north-america-button.jpg'),
  OceaniaButton: require('../images/continents/continentButtons/oceania-button.jpg'),
  SouthAmericaButton: require('../images/continents/continentButtons/south-america-button.jpg'),
}

export const SLEEP = {
  BotswanaSleep: require('../images/continents/africa/botswana/botswana-sleep.jpg'),
  EgyptSleep: require('../images/continents/africa/egypt/egypt-sleep.jpg'),
  KenyaSleep: require('../images/continents/africa/kenya/kenya-sleep.jpg'),
  NamibiaSleep: require('../images/continents/africa/namibia/namibia-sleep.jpg'),
  TanzaniaSleep: require('../images/continents/africa/tanzania/tanzania-sleep.jpg'),
  SouthAfricaSleep: require('../images/continents/africa/south-africa/south-africa-sleep.jpg'),
  CambodiaSleep: require('../images/continents/asia/cambodia/cambodia-sleep.jpg'),
  IndonesiaSleep: require('../images/continents/asia/indonesia/indonesia-sleep.jpg'),
  JapanSleep: require('../images/continents/asia/japan/japan-sleep.jpg'),
  MalaysiaSleep: require('../images/continents/asia/malaysia/malaysia-sleep.jpg'),
  NepalSleep: require('../images/continents/asia/nepal/nepal-sleep.jpg'),
  PhilippinesSleep: require('../images/continents/asia/philippines/philippines-sleep.jpg'),
  ThailandSleep: require('../images/continents/asia/thailand/thailand-sleep.jpg'),
  ItalySleep: require('../images/continents/europe/italy/italy-sleep.jpg'),
  MaltaSleep: require('../images/continents/europe/malta/malta-sleep.jpg'),
  PeruSleep: require('../images/continents/south-america/peru/peru-sleep.jpg'),
  BoliviaSleep: require('../images/continents/south-america/bolivia/bolivia-sleep.jpg'),
  EcuadorSleep: require('../images/continents/south-america/ecuador/ecuador-sleep.jpg'),
}