export const IMAGES = {
  LlamaSocksBanner: require('../images/banners/llamasocks3.jpg'),
  BotswanaButton: require('../images/continents/africa/botswana/botswana-button.jpg'),
  // Africa: require('../images/continents/africa.jpg'),
  // Asia: require('../images/continents/asia.jpg'),
  // Australia: require('../images/continents/australia.jpg'),
  // Europe: require('../images/continents/europe.jpg'),
}

export const BANNER_CAROUSEL = {
  Banner_1: require('../images/banners/llamasocks1.jpg'),
  Banner_2: require('../images/banners/llamasocks2.jpg'),
  Banner_3: require('../images/banners/llamasocks3.jpg'),
  Banner_4: require('../images/banners/llamasocks4.jpg'),
  Banner_5: require('../images/banners/llamasocks5.jpg'),
  Banner_6: require('../images/banners/llamasocks6.jpg'),
  Banner_7: require('../images/banners/llamasocks7.jpg'),
}

export const CONTINENT_BANNERS = {
  AfricaBanner: require('../images/continents/continentBanners/africa-banner.jpg'),
  AsiaBanner: require('../images/continents/continentBanners/asia-banner.jpg'),
  EuropeBanner: require('../images/continents/continentBanners/europe-banner.jpg'),
  NorthAmericaBanner: require('../images/continents/continentBanners/north-america-banner.jpg'),
  SouthAmericaBanner: require('../images/continents/continentBanners/south-america-banner.jpg'),
}

export const CONTINENT_BUTTONS = {
  AfricaButton: require('../images/continents/continentButtons/africa-button.jpg'),
  AsiaButton: require('../images/continents/continentButtons/asia-button.jpg'),
  EuropeButton: require('../images/continents/continentButtons/europe-button.jpg'),
  NorthAmericaButton: require('../images/continents/continentButtons/north-america-button.jpg'),
  OceaniaButton: require('../images/continents/continentButtons/oceania-button.jpg'),
  SouthAmericaButton: require('../images/continents/continentButtons/south-america-button.jpg'),
}

export const COUNTRY_BANNERS = {
  BotswanaBanner: require('../images/continents/africa/botswana/botswana-banner.jpg'),
  EgyptBanner: require('../images/continents/africa/egypt/egypt-banner.jpg'),
  KenyaBanner: require('../images/continents/africa/kenya/kenya-banner.jpg'),
  NamibiaBanner: require('../images/continents/africa/namibia/namibia-banner.jpg'),
  SouthAfricaBanner: require('../images/continents/africa/south-africa/south-africa-banner.jpg'),
  TanzaniaBanner: require('../images/continents/africa/tanzania/tanzania-banner.jpg'),
  CambodiaBanner: require('../images/continents/asia/cambodia/cambodia-banner.jpg'),
  IndonesiaBanner: require('../images/continents/asia/indonesia/indonesia-banner.jpg'),
  JapanBanner: require('../images/continents/asia/japan/japan-banner.jpg'),
  MalaysiaBanner: require('../images/continents/asia/malaysia/malaysia-banner.jpg'),
  NepalBanner: require('../images/continents/asia/nepal/nepal-banner.jpg'),
  PhilippinesBanner: require('../images/continents/asia/philippines/philippines-banner.jpg'),
  ThailandBanner: require('../images/continents/asia/thailand/thailand-banner.jpg'),
  ItalyBanner: require('../images/continents/europe/italy/italy-banner.jpg'),
  MaltaBanner: require('../images/continents/europe/malta/malta-banner.jpg'),
  BoliviaBanner: require('../images/continents/south-america/bolivia/bolivia-banner.jpg'),
  EcuadorBanner: require('../images/continents/south-america/ecuador/ecuador-banner.jpg'),
  PeruBanner: require('../images/continents/south-america/peru/peru-banner.jpg'),
}

export const COUNTRY_BUTTONS = {
  AustraliaButton: require('../images/continents/oceania/australia/australia-button.jpg'),
  BelizeButton: require('../images/continents/north-america/belize/belize-button.jpg'),
  BoliviaButton: require('../images/continents/south-america/bolivia/bolivia-button.jpg'),
  BotswanaButton: require('../images/continents/africa/botswana/botswana-button.jpg'),
  CambodiaButton: require('../images/continents/asia/cambodia/cambodia-button.jpg'),
  EcuadorButton: require('../images/continents/south-america/ecuador/ecuador-button.jpg'),
  EgyptButton: require('../images/continents/africa/egypt/egypt-button.jpg'),
  IndonesiaButton: require('../images/continents/asia/indonesia/indonesia-button.jpg'),
  ItalyButton: require('../images/continents/europe/italy/italy-button.jpg'),
  KenyaButton: require('../images/continents/africa/kenya/kenya-button.jpg'),
  MaltaButton: require('../images/continents/europe/malta/malta-button.jpg'),
  NamibiaButton: require('../images/continents/africa/namibia/namibia-button.jpg'),
  NewZealandButton: require('../images/continents/oceania/new-zealand/new-zealand-button.jpg'),
  PeruButton: require('../images/continents/south-america/peru/peru-button.jpg'),
  SouthAfricaButton: require('../images/continents/africa/south-africa/south-africa-button.jpg'),
  TanzaniaButton: require('../images/continents/africa/tanzania/tanzania-button.jpg'),
  UnitedStatesButton: require('../images/continents/north-america/united-states/united-states-button.jpg'),
  JapanButton: require('../images/continents/asia/japan/japan-button.jpg'),
  MalaysiaButton: require('../images/continents/asia/malaysia/malaysia-button.jpg'),
  NepalButton: require('../images/continents/asia/nepal/nepal-button.jpg'),
  PhilippinesButton: require('../images/continents/asia/philippines/philippines-button.jpg'),
  ThailandButton: require('../images/continents/asia/thailand/thailand-button.jpg'),
}

export const TOP5FRONT = {
  Botswana: {
    1: require('../images/continents/africa/botswana/top5/chobe-top-front.jpg'),
    2: require('../images/continents/africa/botswana/top5/ckgr-top-front.jpg'),
    3: require('../images/continents/africa/botswana/top5/nxai-top-front.jpg'),
    4: require('../images/continents/africa/botswana/top5/okavango-top-front.jpg'),
    5: require('../images/continents/africa/botswana/top5/tsodilo-top-front.jpg'),
  },
  Egypt: {
    1: require('../images/continents/africa/egypt/top5/giza-top-front.jpg'),
    2: require('../images/continents/africa/egypt/top5/egyptdeserts-top-front.jpg'),
    3: require('../images/continents/africa/egypt/top5/nile-top-front.jpg'),
    4: require('../images/continents/africa/egypt/top5/dashur-top-front.jpg'),
    5: require('../images/continents/africa/egypt/top5/abusimbel-top-front.jpg'),
  },
  Kenya: {
    1: require('../images/continents/africa/kenya/top5/masaitop.jpg'),
    2: require('../images/continents/africa/kenya/top5/dianitop.jpg'),
    3: require('../images/continents/africa/kenya/top5/kilifitop.jpg'),
    4: require('../images/continents/africa/kenya/top5/merutop.jpg'),
    5: require('../images/continents/africa/kenya/top5/lamutop.jpg'),
  },
  Namibia: {
    1: require('../images/continents/africa/namibia/top5/sossosvlei-top-front.jpg'),
    2: require('../images/continents/africa/namibia/top5/kolmanskop-top-front.jpg'),
    3: require('../images/continents/africa/namibia/top5/desert-top-front.jpg'),
    4: require('../images/continents/africa/namibia/top5/etosha-top-front.jpg'),
    5: require('../images/continents/africa/namibia/top5/twyfelfontein-top-front.jpg'),
  },
  SouthAfrica: {
    1: require('../images/continents/africa/south-africa/top5/capetowntop.jpg'),
    2: require('../images/continents/africa/south-africa/top5/drakensbergtop.jpg'),
    3: require('../images/continents/africa/south-africa/top5/krugertop.jpg'),
    4: require('../images/continents/africa/south-africa/top5/johannesburgtop.jpg'),
    5: require('../images/continents/africa/south-africa/top5/wildcoasttop.jpg'),
  },
  Tanzania: {
    1: require('../images/continents/africa/tanzania/top5/tazaratop.jpg'),
    2: require('../images/continents/africa/tanzania/top5/zanzibartop.jpg'),
    3: require('../images/continents/africa/tanzania/top5/ngorogorotop.jpg'),
    4: require('../images/continents/africa/tanzania/top5/tanganyikatop.jpg'),
    5: require('../images/continents/africa/tanzania/top5/kilimanjarotop.jpg'),
  },
  Bolivia: {
    1: require('../images/continents/south-america/bolivia/top5/lapaztop.jpg'),
    2: require('../images/continents/south-america/bolivia/top5/uyunitop.jpg'),
    3: require('../images/continents/south-america/bolivia/top5/tiwanakutop.jpg'),
    4: require('../images/continents/south-america/bolivia/top5/islatop.jpg'),
    5: require('../images/continents/south-america/bolivia/top5/amazontop.jpg'),
  },
  Ecuador: {
    1: require('../images/continents/south-america/ecuador/top5/quitotop.jpg'),
    2: require('../images/continents/south-america/ecuador/top5/cuencatop.jpg'),
    3: require('../images/continents/south-america/ecuador/top5/galapagostop.jpg'),
    4: require('../images/continents/south-america/ecuador/top5/coasttop.jpg'),
    5: require('../images/continents/south-america/ecuador/top5/guayaquiltop.jpg'),
  },
  Peru: {
    1: require('../images/continents/south-america/peru/top5/machupicchutop.jpg'),
    2: require('../images/continents/south-america/peru/top5/amazontop.jpg'),
    3: require('../images/continents/south-america/peru/top5/nazcatop.jpg'),
    4: require('../images/continents/south-america/peru/top5/sacredvalleytop.jpg'),
    5: require('../images/continents/south-america/peru/top5/huacachinatop.jpg'),
  },
  Italy: {
    1: require('../images/continents/europe/italy/top5/puglia-top.jpg'),
    2: require('../images/continents/europe/italy/top5/sicily-top.jpg'),
    3: require('../images/continents/europe/italy/top5/rome-top.jpg'),
    4: require('../images/continents/europe/italy/top5/pompeii-top.jpg'),
    5: require('../images/continents/europe/italy/top5/alpedisiusi-top.jpg'),
  },
  Malta: {
    1: require('../images/continents/europe/malta/top5/mdina-top.jpg'),
    2: require('../images/continents/europe/malta/top5/ggantija-top.jpg'),
    3: require('../images/continents/europe/malta/top5/valletta-top.jpg'),
    4: require('../images/continents/europe/malta/top5/elfaroud-top.jpg'),
    5: require('../images/continents/europe/malta/top5/victoria-top.jpg'),
  },
  Cambodia: {
    1: require('../images/continents/asia/cambodia/top5/phnompenhtop.jpg'),
    2: require('../images/continents/asia/cambodia/top5/otrestop.jpg'),
    3: require('../images/continents/asia/cambodia/top5/kohrongtop.jpg'),
    4: require('../images/continents/asia/cambodia/top5/kampottop.jpg'),
    5: require('../images/continents/asia/cambodia/top5/angkortop.jpg'),
  },
  Indonesia: {
    1: require('../images/continents/asia/indonesia/top5/pulauwehtop.jpg'),
    2: require('../images/continents/asia/indonesia/top5/bukittop.jpg'),
    3: require('../images/continents/asia/indonesia/top5/togeantop.jpg'),
    4: require('../images/continents/asia/indonesia/top5/komodotop.jpg'),
    5: require('../images/continents/asia/indonesia/top5/borotop.jpg'),
  },
  Japan: {
    1: require('../images/continents/asia/japan/top5/tokyotop.jpg'),
    2: require('../images/continents/asia/japan/top5/naganotop.jpg'),
    3: require('../images/continents/asia/japan/top5/tsurutop.jpg'),
    4: require('../images/continents/asia/japan/top5/nobotop.jpg'),
    5: require('../images/continents/asia/japan/top5/yonagunitop.jpg'),
  },
  Malaysia: {
    1: require('../images/continents/asia/malaysia/top5/kualatop.jpg'),
    2: require('../images/continents/asia/malaysia/top5/sepiloktop.jpg'),
    3: require('../images/continents/asia/malaysia/top5/penangtop.jpg'),
    4: require('../images/continents/asia/malaysia/top5/tobtop.jpg'),
    5: require('../images/continents/asia/malaysia/top5/sipidantop.jpg'),
  },
  Nepal: {
    1: require('../images/continents/asia/nepal/top5/kathmandutop.jpg'),
    2: require('../images/continents/asia/nepal/top5/bandipurtop.jpg'),
    3: require('../images/continents/asia/nepal/top5/pokharatop.jpg'),
    4: require('../images/continents/asia/nepal/top5/bhaktapurtop.jpg'),
    5: require('../images/continents/asia/nepal/top5/annapurnatop.jpg'),
  },
  Thailand: {
    1: require('../images/continents/asia/thailand/top5/angthongtop.jpg'),
    2: require('../images/continents/asia/thailand/top5/kohphayamtop.jpg'),
    3: require('../images/continents/asia/thailand/top5/ayutthayatop.jpg'),
    4: require('../images/continents/asia/thailand/top5/paitop.jpg'),
    5: require('../images/continents/asia/thailand/top5/railehtop.jpg'),
  },
  Philippines: {
    1: require('../images/continents/asia/philippines/top5/camiguintop.jpg'),
    2: require('../images/continents/asia/philippines/top5/banauetop.jpg'),
    3: require('../images/continents/asia/philippines/top5/elnidotop.jpg'),
    4: require('../images/continents/asia/philippines/top5/corontop.jpg'),
    5: require('../images/continents/asia/philippines/top5/sanvicentetop.jpg'),
  },
}

export const TOP5BANNER = {
  Bolivia: {
    1: require('../images/continents/south-america/bolivia/top5content/lapaz-banner.jpg'),
    2: require('../images/continents/south-america/bolivia/top5content/uyuni-banner.jpg'),
    3: require('../images/continents/south-america/bolivia/top5content/tiwanaku-banner.jpg'),
    4: require('../images/continents/south-america/bolivia/top5content/isladelsol-banner.jpg'),
    5: require('../images/continents/south-america/bolivia/top5content/amazon-banner.jpg'),
  },
  Botswana: {
    1: require('../images/continents/africa/botswana/top5content/chobe-banner.jpg'),
    2: require('../images/continents/africa/botswana/top5content/ckgr-banner.jpg'),
    3: require('../images/continents/africa/botswana/top5content/nxai-banner.jpg'),
    4: require('../images/continents/africa/botswana/top5content/okavango-banner.jpg'),
    5: require('../images/continents/africa/botswana/top5content/tsodilo-banner.jpg'),
  },
  Cambodia: {
    1: require('../images/continents/asia/cambodia/top5content/phnom-penh-banner.jpg'),
    2: require('../images/continents/asia/cambodia/top5content/otres-beach-banner.jpg'),
    3: require('../images/continents/asia/cambodia/top5content/koh-rong-banner.jpg'),
    4: require('../images/continents/asia/cambodia/top5content/kampot-banner.jpg'),
    5: require('../images/continents/asia/cambodia/top5content/angkor-wat-banner.jpg'),
  },
  Ecuador: {
    1: require('../images/continents/south-america/ecuador/top5content/quito-banner.jpg'),
    2: require('../images/continents/south-america/ecuador/top5content/cuenca-banner.jpg'),
    3: require('../images/continents/south-america/ecuador/top5content/galapagos-banner.jpg'),
    4: require('../images/continents/south-america/ecuador/top5content/coast-banner.jpg'),
    5: require('../images/continents/south-america/ecuador/top5content/guayaquil-banner.jpg'),
  },
  Egypt: {
    1: require('../images/continents/africa/egypt/top5content/giza-banner.jpg'),
    2: require('../images/continents/africa/egypt/top5content/egyptdeserts-banner.jpg'),
    3: require('../images/continents/africa/egypt/top5content/nile-banner.jpg'),
    4: require('../images/continents/africa/egypt/top5content/dashur-banner.jpg'),
    5: require('../images/continents/africa/egypt/top5content/abusimbel-banner.jpg'),
  },
  Indonesia: {
    1: require('../images/continents/asia/indonesia/top5content/pulau-weh-banner.jpg'),
    2: require('../images/continents/asia/indonesia/top5content/bukit-lawang-banner.jpg'),
    3: require('../images/continents/asia/indonesia/top5content/togean-islands-banner.jpg'),
    4: require('../images/continents/asia/indonesia/top5content/komodo-banner.jpg'),
    5: require('../images/continents/asia/indonesia/top5content/borobudur-banner.jpg'),
  },
  Italy: {
    1: require('../images/continents/europe/italy/top5content/puglia-banner.jpg'),
    2: require('../images/continents/europe/italy/top5content/sicily-banner.jpg'),
    3: require('../images/continents/europe/italy/top5content/rome-banner.jpg'),
    4: require('../images/continents/europe/italy/top5content/pompeii-banner.jpg'),
    5: require('../images/continents/europe/italy/top5content/alpedisiusi-banner.jpg'),
  },
  Japan: {
    1: require('../images/continents/asia/japan/top5content/tokyo-banner.jpg'),
    2: require('../images/continents/asia/japan/top5content/nagano-banner.jpg'),
    3: require('../images/continents/asia/japan/top5content/tsurunoyu-banner.jpg'),
    4: require('../images/continents/asia/japan/top5content/noboribetsu-banner.jpg'),
    5: require('../images/continents/asia/japan/top5content/yonaguni-banner.jpg'),
  },
  Kenya: {
    1: require('../images/continents/africa/kenya/top5content/masai-banner.jpg'),
    2: require('../images/continents/africa/kenya/top5content/diani-banner.jpg'),
    3: require('../images/continents/africa/kenya/top5content/kilifi-banner.jpg'),
    4: require('../images/continents/africa/kenya/top5content/meru-banner.jpg'),
    5: require('../images/continents/africa/kenya/top5content/lamu-banner.jpg'),
  },
  Malaysia: {
    1: require('../images/continents/asia/malaysia/top5content/kuala-lumpur-banner.jpg'),
    2: require('../images/continents/asia/malaysia/top5content/sepilok-banner.jpg'),
    3: require('../images/continents/asia/malaysia/top5content/penang-banner.jpg'),
    4: require('../images/continents/asia/malaysia/top5content/tip-of-borneo-banner.jpg'),
    5: require('../images/continents/asia/malaysia/top5content/sipidan-banner.jpg'),
  },
  Malta: {
    1: require('../images/continents/europe/malta/top5content/mdina-banner.jpg'),
    2: require('../images/continents/europe/malta/top5content/ggantija-banner.jpg'),
    3: require('../images/continents/europe/malta/top5content/valletta-banner.jpg'),
    4: require('../images/continents/europe/malta/top5content/elfaroud-banner.jpg'),
    5: require('../images/continents/europe/malta/top5content/victoria-banner.jpg'),
  },
  Namibia: {
    1: require('../images/continents/africa/namibia/top5content/sossosvlei-banner.jpg'),
    2: require('../images/continents/africa/namibia/top5content/kolmanskop-banner.jpg'),
    3: require('../images/continents/africa/namibia/top5content/desert-banner.jpg'),
    4: require('../images/continents/africa/namibia/top5content/etosha-banner.jpg'),
    5: require('../images/continents/africa/namibia/top5content/twyfelfontein-banner.jpg'),
  },
  Nepal: {
    1: require('../images/continents/asia/nepal/top5content/kathmandu-banner.jpg'),
    2: require('../images/continents/asia/nepal/top5content/bandipur-banner.jpg'),
    3: require('../images/continents/asia/nepal/top5content/pokhara-banner.jpg'),
    4: require('../images/continents/asia/nepal/top5content/bhaktapur-banner.jpg'),
    5: require('../images/continents/asia/nepal/top5content/annapurnas-banner.jpg'),
  },
  Philippines: {
    1: require('../images/continents/asia/philippines/top5content/camiguin-banner.jpg'),
    2: require('../images/continents/asia/philippines/top5content/banaue-banner.jpg'),
    3: require('../images/continents/asia/philippines/top5content/el-nido-banner.jpg'),
    4: require('../images/continents/asia/philippines/top5content/coron-banner.jpg'),
    5: require('../images/continents/asia/philippines/top5content/san-vicente-banner.jpg'),
  },
  Peru: {
    1: require('../images/continents/south-america/peru/top5content/machupicchu-banner.jpg'),
    2: require('../images/continents/south-america/peru/top5content/amazon-banner.jpg'),
    3: require('../images/continents/south-america/peru/top5content/nazca-banner.jpg'),
    4: require('../images/continents/south-america/peru/top5content/sacredvalley-banner.jpg'),
    5: require('../images/continents/south-america/peru/top5content/huacachina-banner.jpg'),
  },
  SouthAfrica: {
    1: require('../images/continents/africa/south-africa/top5content/capetown-banner.jpg'),
    2: require('../images/continents/africa/south-africa/top5content/drakensberg-banner.jpg'),
    3: require('../images/continents/africa/south-africa/top5content/kruger-banner.jpg'),
    4: require('../images/continents/africa/south-africa/top5content/johannesburg-banner.jpg'),
    5: require('../images/continents/africa/south-africa/top5content/wildcoast-banner.jpg'),
  },
  Tanzania: {
    1: require('../images/continents/africa/tanzania/top5content/tazara-banner.jpg'),
    2: require('../images/continents/africa/tanzania/top5content/zanzibar-banner.jpg'),
    3: require('../images/continents/africa/tanzania/top5content/ngorogoro-banner.jpg'),
    4: require('../images/continents/africa/tanzania/top5content/tanganyika-banner.jpg'),
    5: require('../images/continents/africa/tanzania/top5content/kilimanjaro-banner.jpg'),
  },
  Thailand: {
    1: require('../images/continents/asia/thailand/top5content/ang-thong-banner.jpg'),
    2: require('../images/continents/asia/thailand/top5content/koh-phayam-banner.jpg'),
    3: require('../images/continents/asia/thailand/top5content/ayutthaya-banner.jpg'),
    4: require('../images/continents/asia/thailand/top5content/pai-banner.jpg'),
    5: require('../images/continents/asia/thailand/top5content/raileh-banner.jpg'),
  },
}

// export {IMAGES, COUNTRY_BANNERS};